MegaSiteMVC/Controllers/OrdersController.cs
using MegaSiteMVC.Data.Cart;
using MegaSiteMVC.Data.Services;
using MegaSiteMVC.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MegaSiteMVC.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IProductsService _productsService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IProductsService productsService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _productsService = productsService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                TotalPrice = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _productsService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _productsService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

MegaSiteMVC/Controllers/ProductsController.cs
using MegaSiteMVC.Data;
using MegaSiteMVC.Data.Services;
using MegaSiteMVC.Data.Static;
using MegaSiteMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace MegaSiteMVC.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProductsController : Controller
	{
		private readonly IProductsService _service;

		public ProductsController(IProductsService service)
		{
            _service = service;
		}

        [AllowAnonymous]
        public async Task<IActionResult> Index()
		{
			var data = await _service.GetAllAsync();
			return View(data);
		}

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var products = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filter = products.Where(n => n.Name!.ToLower().Contains(searchString.ToLower()) || n.Description!.ToLower().Contains(searchString.ToLower()));
                products = filter != null? await filter.ToAsyncEnumerable().ToListAsync() : products;
            }

            return View("Index", products);
        }

        public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create([Bind("ImageURL,Name,Description,Price")]Product product)
		{
			if (!ModelState.IsValid)
			{
				return View(product);
			}
			await _service.AddAsync(product);
			return RedirectToAction(nameof(Index));
		}

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
		{
			var product = await _service.GetProductByIdAsync(id);
			return product == null? View("NotFound") : View(product);
		}

        public async Task<IActionResult> Edit(int id)
        {
            var product = await _service.GetProductByIdAsync(id);
            return product == null ? View("NotFound") : View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, ImageURL,Name,Description,Price")] Product product)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }
            await _service.UpdateAsync(id, product);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var product = await _service.GetProductByIdAsync(id);
            return product == null ? View("NotFound") : View(product);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
			var product = await _service.GetProductByIdAsync(id);
			if (product == null)
				return View("NotFound");
			await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MegaSiteMVC/Controllers/TableNotesController.cs
using MegaSiteMVC.Data;
using MegaSiteMVC.Data.Services;
using MegaSiteMVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace MegaSiteMVC.Controllers
{
    public class TableNotesController : Controller
    {
        private readonly ITableNotesService _service;

        public TableNotesController(ITableNotesService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            string jsonSave = _service.ReadJson();
            TableNotes notes = JsonConvert.DeserializeObject<TableNotes>(jsonSave);
            return View(notes);
        }

        [HttpPost]
        public IActionResult Index(TableNotes newNotes)
        {
            string jsonString = JsonConvert.SerializeObject(newNotes);
            _service.WriteJson(jsonString);
            return View(newNotes);
        }
    }
}

MegaSiteMVC/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Product not found";
}

<div class="text-center">
    <h1 class="text-info">You'he reached the end of the internet</h1>
    <hr />
    <a class="btn btn-outline-success" asp-controller="Home" asp-action="Index">Home Page</a>
</div>

MegaSiteMVC/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

<ul class="header__items">
    @if (!User.Identity.IsAuthenticated)
    {
        <li class="header__item">
            <a asp-controller="Account" asp-action="Login">
                <img class="header__item" src="~/images/LogIn.png">
            </a>
        </li>
        <li class="header__item">
            <a asp-controller="Account" asp-action="Register">
                <img class="header__item" src="~/images/Register.png">
            </a>
        </li>
    }
    else
    {
        @if (User.IsInRole("Admin"))
        {
            <li class="header__item">
                <a asp-controller="Account" asp-action="Users">
                    <img class="header__item" src="~/images/Users.png">
                </a>
            </li>
        }

        <li class="header__item">
            <a asp-controller="Orders" asp-action="ShoppingCart">
                <img class="header__item" src="~/images/cart.png">
            </a>
        </li>

        


        <li class="header__item">
            <a asp-controller="Orders" asp-action="Index">
                <img class="header__item" src="/images/Profile.png" alt="ICON">
            </a>
        </li>

        <li class="header__item">
            <a asp-controller="Account" asp-action="Logout">
                <img class="header__item" src="~/images/LogOut.png">
            </a>
        </li>
    }
</ul>

MegaSiteMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Создаватель</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/nav bar.css" asp-append-version="true" />
@*    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/MegaSiteMVC.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header class="header">
        <input type="checkbox" id="nav-toggle" hidden>
        <div class="nav">

            <label for="nav-toggle" class="nav-toggle" onclick></label>

            <a asp-area="" asp-controller="Home" asp-action="Index" class="header__logo">
                <img class="header__logo" src="/images/Logo.png" alt="LOGO">
            </a>
            <ul>
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <li><a asp-area="" asp-controller="Products" asp-action="Index">Shop</a>
                <li><a asp-area="" asp-controller="TableNotes" asp-action="Index">Note table</a>
                <li><a href="#4">Contact</a>
                <li><a asp-controller="Orders" asp-action="ShoppingCart">Cart</a>
                <li><a asp-controller="Orders" asp-action="Index">Profile</a>
            </ul>
        </div>
        <div class="header__main">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="header__logo">
                <img class="header__logo" src="/images/Logo.png" alt="LOGO">
            </a>
            <form class="search__item" asp-controller="Products" asp-action="Filter" method="get">
                <input name="searchString" type="text" class="search__line" placeholder="Search for a product..." aria-label="Recipient's username" aria-describedby="button-addon2">
                <button class="search__button" type="submit"><img src="/images/loup.png" alt="search!"></button>
            </form>
            <partial name="_Identity.cshtml" />
        </div>
        <ul class="navbar">
            <li><a asp-area="" asp-controller="Home" asp-action="Index" class="navbar__item">Home</a></li>
            <li><a asp-area="" asp-controller="Products" asp-action="Index" class="navbar__item">Shop</a></li>
            <li><a asp-area="" asp-controller="TableNotes" asp-action="Index" class="navbar__item">Note table</a></li>
            <li><a href="#links" class="navbar__item">Contact</a></li>
        </ul>
    </header>

    <main role="main">
        @RenderBody()
    </main>


    <footer class="border__top">
        <div>
            &copy; 2022 - Создаватель - <a href="#">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>